#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../parse-domain@8.3.0/node_modules/parse-domain/bin/update.js" "$@"
else
  exec node  "$basedir/../../../../../../parse-domain@8.3.0/node_modules/parse-domain/bin/update.js" "$@"
fi
